#https://acraven.medium.com/a-nuget-package-workflow-using-github-actions-7da8c6557863
name: Publish to NuGet
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+(-(alpha|beta|rc)[0-9]+)?"

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main
    
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    
    - name: Restore
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --configuration Release --no-build
    
    - name: Pack
      run: dotnet pack -v normal -c Release --include-symbols --include-source -p:PackageVersion=${VERSION} -o nupkg src/Flaeng.Umbraco.ContentAPI.csproj
    
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    
    - name: Publish
      run: dotnet nuget push nupkg/Flaeng.Umbraco.ContentAPI.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}