name: Format, build and test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - run: dotnet format          
      - name: Commit formatting
        run: |
          git config --global user.name '@Flaeng'
          git config --global user.email 'flaeng@users.noreply.github.com'
          git commit -am "Formatted code"
          git push
          
  build-and-test:
    runs-on: ubuntu-latest
    needs: [format]
    if: always() && needs.format.result == 'failure'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - run: dotnet build
      - run: dotnet test